// gia-pha-viet-app/src/types/family.d.ts

import { BaseAuditableDto, BaseSearchQuery } from './common';
import { FamilyLimitConfigurationDto } from './familyLimitConfiguration.d'; // Import the new DTO

export enum FamilyRole {
  Manager = 0,
  Viewer = 1,
  Admin = 2,
}

export interface FamilyUserDto {
  familyId?: string;
  userId: string;
  email?: string;
  userName?: string;
  role: FamilyRole;
}

export interface FamilyDetailDto extends BaseAuditableDto {
  id: string;
  name: string;
  code: string;
  description?: string;
  address?: string;
  avatarUrl?: string;
  visibility: string;
  totalMembers: number;
  totalGenerations: number;
  familyUsers: FamilyUserDto[];
  managerIds: [];
  viewerIds: [];
  familyLimitConfiguration?: FamilyLimitConfigurationDto; // Add this property
}

export interface FamilyListDto extends BaseAuditableDto {
  id: string;
  name: string;
  description?: string;
  address?: string;
  avatarUrl?: string;
  totalMembers: number;
  totalGenerations: number;
  visibility: string;

}

export interface FamilyCreateRequestDto {
  name: string;
  description?: string;
  address?: string;
  avatarUrl?: string;
  avatarBase64?: string; // Optional, only present if image is uploaded
  visibility: string;
  familyUsers: FamilyUserDto[];
}

export interface FamilyUpdateRequestDto {
  id: string; // ID is required for update
  name: string;
  description?: string;
  address?: string;
  avatarUrl?: string;
  avatarBase64?: string; // Optional for update
  visibility: string;
  familyUsers: FamilyUserDto[];
  code?: string; // Code might be sent back for update, but not generated by frontend
}

export interface SearchFamiliesQuery extends BaseSearchQuery { }
